pull request for TSE review
muhenge/Newsweek-clone pull request #6
Opened 2020-01-03 15:24 UTC by muhenge

2020-01-03 16:31 UTC, suretrust requested changes
Hi @muhenge,

### Great job thus far. 🙌 Please see my comments on your code.

**Kindly submit for another code review once these issues have been resolved.** _Happy coding!_ 🎉

2020-01-03 16:31 UTC, suretrust commented on index.html
> +                    </button>
##### Navigation bar
* [ ] **It changes with RWD breakpoints** ([link to page](https://www.newsweek.com/)). Your navbar is not properly sized and contains sub navbar on the medium screen.

**Yours**
<img width="854" alt="Screenshot 2020-01-03 at 17 12 15" src="https://user-images.githubusercontent.com/31304943/71734404-359b8c00-2e4c-11ea-80d8-f8f21275dcb1.png">


**Original**
<img width="981" alt="Screenshot 2020-01-03 at 17 11 27" src="https://user-images.githubusercontent.com/31304943/71734384-20266200-2e4c-11ea-9958-304fd9de994d.png">

2020-01-03 16:31 UTC, suretrust commented on index.html
> +                                            src="https://d.newsweek.com/en/full/1548831/fe-csr-01-1041330598-banner.webp?w=466&h=311&l=52&t=49&q=90&f=e6d8a68693cdcf8906bbbe92a804bc55"
The "IN THE MAGAZINE" section is messy on a medium screen. [Link to page](https://www.newsweek.com/).

**Yours**
<img width="854" alt="Screenshot 2020-01-03 at 17 15 48" src="https://user-images.githubusercontent.com/31304943/71734755-e86bea00-2e4c-11ea-8bd7-2b68d553c99d.png">

**Original**
<img width="979" alt="Screenshot 2020-01-03 at 17 16 06" src="https://user-images.githubusercontent.com/31304943/71734775-f28de880-2e4c-11ea-87db-08a1f7901f77.png">

2020-01-03 16:31 UTC, suretrust commented on index.html
> +
##### Footer

* [ ] It contains social media icons ([link to page](https://www.newsweek.com/))
* [ ] **It changes with RWD breakpoints** ([link to page](https://www.newsweek.com/))

2020-01-10 23:48 UTC, izaiasneto4 commented
#### Hi @muhenge. Great job implement all of the required changes. Status: Approved :+1: 

TSE: Izaias Neto

2020-01-10 23:51 UTC, izaiasneto4 commented
### Hi @muhenge. Nice job implementing the requested changes, there's just one thing left to fix before we can get your project approved.  :arrow_down: 

- [ ] Let's fix all of the errors given by the [validator](https://validator.w3.org/nu/#file)

Please, when finished submit the project for a new request. :pray:

2020-01-12 11:21 UTC, mosesogwo approved these changes
### :trophy: Congratulations! You have done well.

Please consider aligning the three columns at the top properly before merging to master. Since this wasn't pointed out before now, I'll give my approval.

![image](https://user-images.githubusercontent.com/46611870/72217997-fbaa4400-3535-11ea-933b-d0d4a6edcba7.png)


Cheers.

### Status: Approved

2020-01-16 06:03 UTC, merged